apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
  namespace: logging
spec:
  version: 7.15.1
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    tls:
      certificate:
        secretName: rocsys-dev-cert
