program: wrkspc

wrkspc:
  stage: development

  stages:
    development:
      errnie:
        local: false
        debug: true
        trace: true

      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"

    test:
      errnie:
        local: false
        debug: true
        trace: true

      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"

    production:
      errnie:
        local: false
        debug: false
        trace: false

      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"


  architectures:
    ingress:
      networking:
        directions:
          - incoming
        connections:
          - http
          - websocket
          - capnproto
      stores:
        - radix
        - minio
        - s3
