program: wrkspc

wrkspc:
  # The current stage to run under.
  stage: local

  # Stage specific configurations.
  stages: {}

  errnie:
    debug: true
    trace: false

  # Configure various elements for the `run` command.
  run:
    pre: |
      # This is just a shell script.
    post: |
      # This is just a shell script.

  kube:
    config: ~/.kube/config
    distro:
      - metallb

  bcknd:
    port: 8008
    read-timeout: 10
    writeTimeout: 10

  # Configure the automatic cluster propagation. Using this feature
  # will automatically take over any machine you have access to on
  # the local network and provision it as a cluster node.
  contempt:
    # All usernames and passwords to try during the making of
    # connections to machines found on the network. These will
    # be tried in all possible combinations. To avoid spamming your
    # ssh daemons with failed logins, have a keypair setup in the
    # default location on your host OS as this will be tried first.
    usernames: []
    passwords: []

  # Configure lexical analyzer.
  lexer:
    # Any character the lexer should recognize as a delimitor in
    # comma separated format.
    delimiters: 
      - "[,]"
      - "::,::"
      - "(,)"
      - "{,}"

    # Known types you want to explicitely group under a certain
    # type for the state model. You can add to this arbitrarily, both values as categories.
    types:
      line-types:
        - logs
      service-types:
        - bcknd
      unit-types:
        - time
      log-types:
        - info
        - debug
      state-types:
        - failed
        - crashed
      action-types:
        - send
        - receive
      direction-types:
        - <=
        - =>
        - <=>

  # Configure simulator scenes.
  scenes:
    randomize-values:
      message: "randomizing values"
      arguments:
        strategy: "dice-roll"
    some-action:
      message: "some action"
    failure-rate:
      message: "applying failure rate"
      arguments:
        percentage: 10
    instance-bcknd:
      message: "instantiate bcknd"
      arguments:
        scope: global
    post-http:
      message: "pushing results"
      arguments:
        ingress: https://ingress.cluster.local/v1/secure

  # Configure simulator scenarios.
  scenarios:
    test:
      scenes:
        - randomize-values
        - plugin-action
        - failure-rate
        - instance-bcknd
        # - post-http