program: wrkspc

wrkspc:
  stage: development

  stages:
    development:
      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"

    test:
      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"

    production:
      server:
        port: "1984"

      s3:
        key: minioadmin
        secret: minioadmin
        region: us-east-2
        bucket: wrkspc
        endpoint: "http://127.0.0.1:9000"

  errnie:
    local: false
    debug: true
    trace: true

  architectures:
    ingress:
      networking:
        directions:
          - incoming
        connections:
          - http
          - websocket
          - capnproto
      stores:
        - radix
        - minio
        - s3
